-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
module('RecastPos_pb')


local RECASTREQ = protobuf.Descriptor();
local RECASTREQ_ID_FIELD = protobuf.FieldDescriptor();
local RECASTREQ_START_FIELD = protobuf.FieldDescriptor();
local RECASTREQ_END_FIELD = protobuf.FieldDescriptor();
local RECASTRES = protobuf.Descriptor();
local RECASTRES_ID_FIELD = protobuf.FieldDescriptor();
local RECASTRES_RESULT_FIELD = protobuf.FieldDescriptor();
local SPRITEPOSRES = protobuf.Descriptor();
local SPRITEPOSRES_ID_FIELD = protobuf.FieldDescriptor();
local SPRITEPOSRES_CURPOS_FIELD = protobuf.FieldDescriptor();

RECASTREQ_ID_FIELD.name = "id"
RECASTREQ_ID_FIELD.full_name = ".com.finger.common.net.proto.RecastReq.id"
RECASTREQ_ID_FIELD.number = 1
RECASTREQ_ID_FIELD.index = 0
RECASTREQ_ID_FIELD.label = 1
RECASTREQ_ID_FIELD.has_default_value = false
RECASTREQ_ID_FIELD.default_value = 0
RECASTREQ_ID_FIELD.type = 5
RECASTREQ_ID_FIELD.cpp_type = 1

RECASTREQ_START_FIELD.name = "start"
RECASTREQ_START_FIELD.full_name = ".com.finger.common.net.proto.RecastReq.start"
RECASTREQ_START_FIELD.number = 2
RECASTREQ_START_FIELD.index = 1
RECASTREQ_START_FIELD.label = 3
RECASTREQ_START_FIELD.has_default_value = false
RECASTREQ_START_FIELD.default_value = {}
RECASTREQ_START_FIELD.type = 2
RECASTREQ_START_FIELD.cpp_type = 6

RECASTREQ_END_FIELD.name = "end"
RECASTREQ_END_FIELD.full_name = ".com.finger.common.net.proto.RecastReq.end"
RECASTREQ_END_FIELD.number = 3
RECASTREQ_END_FIELD.index = 2
RECASTREQ_END_FIELD.label = 3
RECASTREQ_END_FIELD.has_default_value = false
RECASTREQ_END_FIELD.default_value = {}
RECASTREQ_END_FIELD.type = 2
RECASTREQ_END_FIELD.cpp_type = 6

RECASTREQ.name = "RecastReq"
RECASTREQ.full_name = ".com.finger.common.net.proto.RecastReq"
RECASTREQ.nested_types = {}
RECASTREQ.enum_types = {}
RECASTREQ.fields = {RECASTREQ_ID_FIELD, RECASTREQ_START_FIELD, RECASTREQ_END_FIELD}
RECASTREQ.is_extendable = false
RECASTREQ.extensions = {}
RECASTRES_ID_FIELD.name = "id"
RECASTRES_ID_FIELD.full_name = ".com.finger.common.net.proto.RecastRes.id"
RECASTRES_ID_FIELD.number = 1
RECASTRES_ID_FIELD.index = 0
RECASTRES_ID_FIELD.label = 1
RECASTRES_ID_FIELD.has_default_value = false
RECASTRES_ID_FIELD.default_value = 0
RECASTRES_ID_FIELD.type = 5
RECASTRES_ID_FIELD.cpp_type = 1

RECASTRES_RESULT_FIELD.name = "result"
RECASTRES_RESULT_FIELD.full_name = ".com.finger.common.net.proto.RecastRes.result"
RECASTRES_RESULT_FIELD.number = 2
RECASTRES_RESULT_FIELD.index = 1
RECASTRES_RESULT_FIELD.label = 1
RECASTRES_RESULT_FIELD.has_default_value = false
RECASTRES_RESULT_FIELD.default_value = 0
RECASTRES_RESULT_FIELD.type = 5
RECASTRES_RESULT_FIELD.cpp_type = 1

RECASTRES.name = "RecastRes"
RECASTRES.full_name = ".com.finger.common.net.proto.RecastRes"
RECASTRES.nested_types = {}
RECASTRES.enum_types = {}
RECASTRES.fields = {RECASTRES_ID_FIELD, RECASTRES_RESULT_FIELD}
RECASTRES.is_extendable = false
RECASTRES.extensions = {}
SPRITEPOSRES_ID_FIELD.name = "id"
SPRITEPOSRES_ID_FIELD.full_name = ".com.finger.common.net.proto.SpritePosRes.id"
SPRITEPOSRES_ID_FIELD.number = 1
SPRITEPOSRES_ID_FIELD.index = 0
SPRITEPOSRES_ID_FIELD.label = 1
SPRITEPOSRES_ID_FIELD.has_default_value = false
SPRITEPOSRES_ID_FIELD.default_value = 0
SPRITEPOSRES_ID_FIELD.type = 5
SPRITEPOSRES_ID_FIELD.cpp_type = 1

SPRITEPOSRES_CURPOS_FIELD.name = "curPos"
SPRITEPOSRES_CURPOS_FIELD.full_name = ".com.finger.common.net.proto.SpritePosRes.curPos"
SPRITEPOSRES_CURPOS_FIELD.number = 2
SPRITEPOSRES_CURPOS_FIELD.index = 1
SPRITEPOSRES_CURPOS_FIELD.label = 3
SPRITEPOSRES_CURPOS_FIELD.has_default_value = false
SPRITEPOSRES_CURPOS_FIELD.default_value = {}
SPRITEPOSRES_CURPOS_FIELD.type = 2
SPRITEPOSRES_CURPOS_FIELD.cpp_type = 6

SPRITEPOSRES.name = "SpritePosRes"
SPRITEPOSRES.full_name = ".com.finger.common.net.proto.SpritePosRes"
SPRITEPOSRES.nested_types = {}
SPRITEPOSRES.enum_types = {}
SPRITEPOSRES.fields = {SPRITEPOSRES_ID_FIELD, SPRITEPOSRES_CURPOS_FIELD}
SPRITEPOSRES.is_extendable = false
SPRITEPOSRES.extensions = {}

RecastReq = protobuf.Message(RECASTREQ)
RecastRes = protobuf.Message(RECASTRES)
SpritePosRes = protobuf.Message(SPRITEPOSRES)

