//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: input/ice_sProtol.proto
namespace ice_sProtol
{
    [global::ProtoBuf.ProtoContract(Name=@"MSGID")]
    public enum MSGID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CSID_C2L_LOGINSERVER", Value=1020)]
      CSID_C2L_LOGINSERVER = 1020,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CSID_L2C_LOGINSERVER", Value=1021)]
      CSID_L2C_LOGINSERVER = 1021,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CSID_C2S_PUB_BEAT", Value=30100)]
      CSID_C2S_PUB_BEAT = 30100,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CSID_S2C_PUB_BEAT", Value=30101)]
      CSID_S2C_PUB_BEAT = 30101
    }
  
}