// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ice_sProtol.proto

#ifndef PROTOBUF_ice_5fsProtol_2eproto__INCLUDED
#define PROTOBUF_ice_5fsProtol_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
// @@protoc_insertion_point(includes)

namespace ice_sProtol {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_ice_5fsProtol_2eproto();
void protobuf_AssignDesc_ice_5fsProtol_2eproto();
void protobuf_ShutdownFile_ice_5fsProtol_2eproto();


enum MSGID {
  CSID_C2L_LOGINSERVER = 1020,
  CSID_L2C_LOGINSERVER = 1021,
  CSID_C2S_PUB_BEAT = 30100,
  CSID_S2C_PUB_BEAT = 30101
};
bool MSGID_IsValid(int value);
const MSGID MSGID_MIN = CSID_C2L_LOGINSERVER;
const MSGID MSGID_MAX = CSID_S2C_PUB_BEAT;
const int MSGID_ARRAYSIZE = MSGID_MAX + 1;

const ::google::protobuf::EnumDescriptor* MSGID_descriptor();
inline const ::std::string& MSGID_Name(MSGID value) {
  return ::google::protobuf::internal::NameOfEnum(
    MSGID_descriptor(), value);
}
inline bool MSGID_Parse(
    const ::std::string& name, MSGID* value) {
  return ::google::protobuf::internal::ParseNamedEnum<MSGID>(
    MSGID_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================


// @@protoc_insertion_point(namespace_scope)

}  // namespace ice_sProtol

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::ice_sProtol::MSGID> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::ice_sProtol::MSGID>() {
  return ::ice_sProtol::MSGID_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ice_5fsProtol_2eproto__INCLUDED
