//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: light framework (CF/Silverlight) enabled
    
// Generated from: protobuf/auth.proto
namespace com.kz.message.proto
{
  [global::ProtoBuf.ProtoContract(Name=@"LocalLoginReq")]
  public partial class LocalLoginReq : global::ProtoBuf.IExtensible
  {
    public LocalLoginReq() {}
    
    private string _email = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"email", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string email
    {
      get { return _email; }
      set { _email = value; }
    }
    private string _password = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string password
    {
      get { return _password; }
      set { _password = value; }
    }
    private string _randomSeed = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"randomSeed", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string randomSeed
    {
      get { return _randomSeed; }
      set { _randomSeed = value; }
    }
    private string _version = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"version", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string version
    {
      get { return _version; }
      set { _version = value; }
    }
    private int _channelID = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"channelID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int channelID
    {
      get { return _channelID; }
      set { _channelID = value; }
    }
    private com.kz.message.proto.DeviceInfoPro _deviceInfo = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"deviceInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.kz.message.proto.DeviceInfoPro deviceInfo
    {
      get { return _deviceInfo; }
      set { _deviceInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"BindAccountReq")]
  public partial class BindAccountReq : global::ProtoBuf.IExtensible
  {
    public BindAccountReq() {}
    
    private string _email = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"email", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string email
    {
      get { return _email; }
      set { _email = value; }
    }
    private string _password = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string password
    {
      get { return _password; }
      set { _password = value; }
    }
    private string _randomSeed = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"randomSeed", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string randomSeed
    {
      get { return _randomSeed; }
      set { _randomSeed = value; }
    }
    private string _version = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"version", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string version
    {
      get { return _version; }
      set { _version = value; }
    }
    private int _channelID = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"channelID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int channelID
    {
      get { return _channelID; }
      set { _channelID = value; }
    }
    private com.kz.message.proto.DeviceInfoPro _deviceInfo = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"deviceInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.kz.message.proto.DeviceInfoPro deviceInfo
    {
      get { return _deviceInfo; }
      set { _deviceInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"BindAccountRes")]
  public partial class BindAccountRes : global::ProtoBuf.IExtensible
  {
    public BindAccountRes() {}
    
    private int _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"CreateAccountReq")]
  public partial class CreateAccountReq : global::ProtoBuf.IExtensible
  {
    public CreateAccountReq() {}
    
    private string _email = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"email", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string email
    {
      get { return _email; }
      set { _email = value; }
    }
    private string _password = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string password
    {
      get { return _password; }
      set { _password = value; }
    }
    private string _randomSeed = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"randomSeed", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string randomSeed
    {
      get { return _randomSeed; }
      set { _randomSeed = value; }
    }
    private string _version = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"version", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string version
    {
      get { return _version; }
      set { _version = value; }
    }
    private int _channelID = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"channelID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int channelID
    {
      get { return _channelID; }
      set { _channelID = value; }
    }
    private com.kz.message.proto.DeviceInfoPro _deviceInfo = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"deviceInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.kz.message.proto.DeviceInfoPro deviceInfo
    {
      get { return _deviceInfo; }
      set { _deviceInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"CreateAccountRes")]
  public partial class CreateAccountRes : global::ProtoBuf.IExtensible
  {
    public CreateAccountRes() {}
    
    private int _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"ChangePasswordReq")]
  public partial class ChangePasswordReq : global::ProtoBuf.IExtensible
  {
    public ChangePasswordReq() {}
    
    private string _email;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"email", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string email
    {
      get { return _email; }
      set { _email = value; }
    }
    private string _newPassword;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"newPassword", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string newPassword
    {
      get { return _newPassword; }
      set { _newPassword = value; }
    }
    private string _oldPassword;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"oldPassword", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string oldPassword
    {
      get { return _oldPassword; }
      set { _oldPassword = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"ChangePasswordRes")]
  public partial class ChangePasswordRes : global::ProtoBuf.IExtensible
  {
    public ChangePasswordRes() {}
    
    private int _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"DeviceInfoPro")]
  public partial class DeviceInfoPro : global::ProtoBuf.IExtensible
  {
    public DeviceInfoPro() {}
    
    private string _OSType = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"OSType", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string OSType
    {
      get { return _OSType; }
      set { _OSType = value; }
    }
    private string _OSVersion = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"OSVersion", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string OSVersion
    {
      get { return _OSVersion; }
      set { _OSVersion = value; }
    }
    private int _deviceType = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"deviceType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int deviceType
    {
      get { return _deviceType; }
      set { _deviceType = value; }
    }
    private string _UDID = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"UDID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string UDID
    {
      get { return _UDID; }
      set { _UDID = value; }
    }
    private string _deviceName = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"deviceName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string deviceName
    {
      get { return _deviceName; }
      set { _deviceName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"LoginRes")]
  public partial class LoginRes : global::ProtoBuf.IExtensible
  {
    public LoginRes() {}
    
    private int _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private long _accountID = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"accountID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long accountID
    {
      get { return _accountID; }
      set { _accountID = value; }
    }
    private string _token = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string token
    {
      get { return _token; }
      set { _token = value; }
    }
    private readonly global::System.Collections.Generic.List<com.kz.message.proto.AreaPro> _areas = new global::System.Collections.Generic.List<com.kz.message.proto.AreaPro>();
    [global::ProtoBuf.ProtoMember(4, Name=@"areas", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.kz.message.proto.AreaPro> areas
    {
      get { return _areas; }
    }
  
    private int _lastAreaID = (int)-1;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"lastAreaID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int lastAreaID
    {
      get { return _lastAreaID; }
      set { _lastAreaID = value; }
    }
    private bool _isFirstQuickLogin = default(bool);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"isFirstQuickLogin", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isFirstQuickLogin
    {
      get { return _isFirstQuickLogin; }
      set { _isFirstQuickLogin = value; }
    }
    private bool _isShowActivityInterface = default(bool);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"isShowActivityInterface", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isShowActivityInterface
    {
      get { return _isShowActivityInterface; }
      set { _isShowActivityInterface = value; }
    }
    private com.kz.message.proto.ChannelMessagePro _channel = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"channel", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.kz.message.proto.ChannelMessagePro channel
    {
      get { return _channel; }
      set { _channel = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"ChannelMessagePro")]
  public partial class ChannelMessagePro : global::ProtoBuf.IExtensible
  {
    public ChannelMessagePro() {}
    
    private string _accessToken = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"accessToken", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string accessToken
    {
      get { return _accessToken; }
      set { _accessToken = value; }
    }
    private string _channelUniqueId = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"channelUniqueId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string channelUniqueId
    {
      get { return _channelUniqueId; }
      set { _channelUniqueId = value; }
    }
    private string _channelUserName = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"channelUserName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string channelUserName
    {
      get { return _channelUserName; }
      set { _channelUserName = value; }
    }
    private string _oid = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"oid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string oid
    {
      get { return _oid; }
      set { _oid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"AreaPro")]
  public partial class AreaPro : global::ProtoBuf.IExtensible
  {
    public AreaPro() {}
    
    private int _areaID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"areaID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int areaID
    {
      get { return _areaID; }
      set { _areaID = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _status;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int status
    {
      get { return _status; }
      set { _status = value; }
    }
    private string _interfaceServerIP;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"interfaceServerIP", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string interfaceServerIP
    {
      get { return _interfaceServerIP; }
      set { _interfaceServerIP = value; }
    }
    private int _interfaceServerPort;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"interfaceServerPort", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int interfaceServerPort
    {
      get { return _interfaceServerPort; }
      set { _interfaceServerPort = value; }
    }
    private int _areaAvatarNumber = (int)0;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"areaAvatarNumber", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int areaAvatarNumber
    {
      get { return _areaAvatarNumber; }
      set { _areaAvatarNumber = value; }
    }
    private int _showAreaID = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"showAreaID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int showAreaID
    {
      get { return _showAreaID; }
      set { _showAreaID = value; }
    }
    private bool _isNewServer;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"isNewServer", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isNewServer
    {
      get { return _isNewServer; }
      set { _isNewServer = value; }
    }
    private bool _isRecommendServer;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"isRecommendServer", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isRecommendServer
    {
      get { return _isRecommendServer; }
      set { _isRecommendServer = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}