//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: light framework (CF/Silverlight) enabled
    
// Generated from: protobuf/chat.proto
namespace com.kz.message.proto
{
  [global::ProtoBuf.ProtoContract(Name=@"SendChatReq")]
  public partial class SendChatReq : global::ProtoBuf.IExtensible
  {
    public SendChatReq() {}
    
    private int _chatChannel = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"chatChannel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int chatChannel
    {
      get { return _chatChannel; }
      set { _chatChannel = value; }
    }
    private long _targetId = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"targetId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long targetId
    {
      get { return _targetId; }
      set { _targetId = value; }
    }
    private string _contents = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"contents", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string contents
    {
      get { return _contents; }
      set { _contents = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"SendChatRes")]
  public partial class SendChatRes : global::ProtoBuf.IExtensible
  {
    public SendChatRes() {}
    
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"ChatRes")]
  public partial class ChatRes : global::ProtoBuf.IExtensible
  {
    public ChatRes() {}
    
    private com.kz.message.proto.ChatPro _chatPro = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"chatPro", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.kz.message.proto.ChatPro chatPro
    {
      get { return _chatPro; }
      set { _chatPro = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"ChatListRes")]
  public partial class ChatListRes : global::ProtoBuf.IExtensible
  {
    public ChatListRes() {}
    
    private readonly global::System.Collections.Generic.List<com.kz.message.proto.ChatPro> _list = new global::System.Collections.Generic.List<com.kz.message.proto.ChatPro>();
    [global::ProtoBuf.ProtoMember(1, Name=@"list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.kz.message.proto.ChatPro> list
    {
      get { return _list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"ChatPro")]
  public partial class ChatPro : global::ProtoBuf.IExtensible
  {
    public ChatPro() {}
    
    private int _chatChannel = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"chatChannel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int chatChannel
    {
      get { return _chatChannel; }
      set { _chatChannel = value; }
    }
    private long _senderId = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"senderId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long senderId
    {
      get { return _senderId; }
      set { _senderId = value; }
    }
    private string _senderName = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"senderName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string senderName
    {
      get { return _senderName; }
      set { _senderName = value; }
    }
    private long _sentTime = default(long);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"sentTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long sentTime
    {
      get { return _sentTime; }
      set { _sentTime = value; }
    }
    private string _contents = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"contents", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string contents
    {
      get { return _contents; }
      set { _contents = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"SetGagNameListReq")]
  public partial class SetGagNameListReq : global::ProtoBuf.IExtensible
  {
    public SetGagNameListReq() {}
    
    private int _setType = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"setType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int setType
    {
      get { return _setType; }
      set { _setType = value; }
    }
    private long _roleId = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"roleId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long roleId
    {
      get { return _roleId; }
      set { _roleId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"SetGagNameListRes")]
  public partial class SetGagNameListRes : global::ProtoBuf.IExtensible
  {
    public SetGagNameListRes() {}
    
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private int _setType = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"setType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int setType
    {
      get { return _setType; }
      set { _setType = value; }
    }
    private long _roleId = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"roleId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long roleId
    {
      get { return _roleId; }
      set { _roleId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"GagNameListRes")]
  public partial class GagNameListRes : global::ProtoBuf.IExtensible
  {
    public GagNameListRes() {}
    
    private readonly global::System.Collections.Generic.List<com.kz.message.proto.GagNamePro> _list = new global::System.Collections.Generic.List<com.kz.message.proto.GagNamePro>();
    [global::ProtoBuf.ProtoMember(1, Name=@"list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.kz.message.proto.GagNamePro> list
    {
      get { return _list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"GagNamePro")]
  public partial class GagNamePro : global::ProtoBuf.IExtensible
  {
    public GagNamePro() {}
    
    private long _roleId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"roleId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long roleId
    {
      get { return _roleId; }
      set { _roleId = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}