//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: light framework (CF/Silverlight) enabled
    
// Generated from: protobuf/item.proto
namespace com.kz.message.proto
{
  [global::ProtoBuf.ProtoContract(Name=@"UseItemReq")]
  public partial class UseItemReq : global::ProtoBuf.IExtensible
  {
    public UseItemReq() {}
    
    private int _itemId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"itemId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int itemId
    {
      get { return _itemId; }
      set { _itemId = value; }
    }
    private int _itemNum;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"itemNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int itemNum
    {
      get { return _itemNum; }
      set { _itemNum = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"SaleItemReq")]
  public partial class SaleItemReq : global::ProtoBuf.IExtensible
  {
    public SaleItemReq() {}
    
    private int _itemId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"itemId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int itemId
    {
      get { return _itemId; }
      set { _itemId = value; }
    }
    private int _itemCount;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"itemCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int itemCount
    {
      get { return _itemCount; }
      set { _itemCount = value; }
    }
    private long _itemPkId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"itemPkId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long itemPkId
    {
      get { return _itemPkId; }
      set { _itemPkId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"BagPro")]
  public partial class BagPro : global::ProtoBuf.IExtensible
  {
    public BagPro() {}
    
    private readonly global::System.Collections.Generic.List<com.kz.message.proto.ItemPro> _items = new global::System.Collections.Generic.List<com.kz.message.proto.ItemPro>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.kz.message.proto.ItemPro> items
    {
      get { return _items; }
    }
  
    private long _maxPkId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"maxPkId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long maxPkId
    {
      get { return _maxPkId; }
      set { _maxPkId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"ItemPro")]
  public partial class ItemPro : global::ProtoBuf.IExtensible
  {
    public ItemPro() {}
    
    private int _itemId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"itemId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int itemId
    {
      get { return _itemId; }
      set { _itemId = value; }
    }
    private int _itemCount;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"itemCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int itemCount
    {
      get { return _itemCount; }
      set { _itemCount = value; }
    }
    private long _itemPkId = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"itemPkId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long itemPkId
    {
      get { return _itemPkId; }
      set { _itemPkId = value; }
    }
    private long _effectTime = default(long);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"effectTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long effectTime
    {
      get { return _effectTime; }
      set { _effectTime = value; }
    }
    private com.kz.message.proto.EquipItemPro _equipPro = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"equipPro", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.kz.message.proto.EquipItemPro equipPro
    {
      get { return _equipPro; }
      set { _equipPro = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"EquipItemPro")]
  public partial class EquipItemPro : global::ProtoBuf.IExtensible
  {
    public EquipItemPro() {}
    
    private long _shipId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"shipId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long shipId
    {
      get { return _shipId; }
      set { _shipId = value; }
    }
    private int _qhLevel = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"qhLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int qhLevel
    {
      get { return _qhLevel; }
      set { _qhLevel = value; }
    }
    private int _jlLevel = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"jlLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int jlLevel
    {
      get { return _jlLevel; }
      set { _jlLevel = value; }
    }
    private int _jlExp = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"jlExp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int jlExp
    {
      get { return _jlExp; }
      set { _jlExp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"LevelUpEquipReq")]
  public partial class LevelUpEquipReq : global::ProtoBuf.IExtensible
  {
    public LevelUpEquipReq() {}
    
    private long _equipId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"equipId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long equipId
    {
      get { return _equipId; }
      set { _equipId = value; }
    }
    private bool _up1Level;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"up1Level", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool up1Level
    {
      get { return _up1Level; }
      set { _up1Level = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"EquipAllLevelUpRes")]
  public partial class EquipAllLevelUpRes : global::ProtoBuf.IExtensible
  {
    public EquipAllLevelUpRes() {}
    
    private int _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private readonly global::System.Collections.Generic.List<com.kz.message.proto.ItemPro> _item = new global::System.Collections.Generic.List<com.kz.message.proto.ItemPro>();
    [global::ProtoBuf.ProtoMember(2, Name=@"item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.kz.message.proto.ItemPro> item
    {
      get { return _item; }
    }
  
    private int _gold;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int gold
    {
      get { return _gold; }
      set { _gold = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}