//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: light framework (CF/Silverlight) enabled
    
// Generated from: protobuf/login.proto
// Note: requires additional types generated from: protobuf/role.proto
namespace com.kz.message.proto
{
  [global::ProtoBuf.ProtoContract(Name=@"LoginGameReq")]
  public partial class LoginGameReq : global::ProtoBuf.IExtensible
  {
    public LoginGameReq() {}
    
    private string _token;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string token
    {
      get { return _token; }
      set { _token = value; }
    }
    private long _accountId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"accountId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long accountId
    {
      get { return _accountId; }
      set { _accountId = value; }
    }
    private int _areaId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"areaId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int areaId
    {
      get { return _areaId; }
      set { _areaId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"LoginGameRes")]
  public partial class LoginGameRes : global::ProtoBuf.IExtensible
  {
    public LoginGameRes() {}
    
    private int _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private com.kz.message.proto.RoleBaseDataPro _roleData = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"roleData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.kz.message.proto.RoleBaseDataPro roleData
    {
      get { return _roleData; }
      set { _roleData = value; }
    }
    private com.kz.message.proto.GameConfigPro _config = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"config", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.kz.message.proto.GameConfigPro config
    {
      get { return _config; }
      set { _config = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"CreateRoleReq")]
  public partial class CreateRoleReq : global::ProtoBuf.IExtensible
  {
    public CreateRoleReq() {}
    
    private string _roleName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roleName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roleName
    {
      get { return _roleName; }
      set { _roleName = value; }
    }
    private int _spriteId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"spriteId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int spriteId
    {
      get { return _spriteId; }
      set { _spriteId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"CreateRoleRes")]
  public partial class CreateRoleRes : global::ProtoBuf.IExtensible
  {
    public CreateRoleRes() {}
    
    private int _result;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"GameConfigPro")]
  public partial class GameConfigPro : global::ProtoBuf.IExtensible
  {
    public GameConfigPro() {}
    
    private int _jlExp1;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"jlExp1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int jlExp1
    {
      get { return _jlExp1; }
      set { _jlExp1 = value; }
    }
    private int _jlExp2;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"jlExp2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int jlExp2
    {
      get { return _jlExp2; }
      set { _jlExp2 = value; }
    }
    private int _jlExp3;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"jlExp3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int jlExp3
    {
      get { return _jlExp3; }
      set { _jlExp3 = value; }
    }
    private int _jlExp4;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"jlExp4", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int jlExp4
    {
      get { return _jlExp4; }
      set { _jlExp4 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}