//This file is generated by program. Do not edit it manually.

using System;
using System.Collections.Generic;
using System.Text;

namespace com.kz.protocol
{
	public class Protocols
	{
		public static int Type(int id)
		{
			return (int)(0xffff0000 & id);
		}

		public static int IdWithoutType(int id)
		{
			return 0x0000ffff & id;
		}

		public static Boolean isSuccess(int id)
		{
			if(id <= 0)
				return true;
			uint newId = (uint)id;
			return ((id & 0xfff00000)>>20) < 0x10;
		}

		//ServerType 0xxxxx0000
		public const int SERVER_TYPE_AUTH = 0x00020000;
		public const int SERVER_TYP_GAME = 0x00030000;
		public const int SERVER_TYPE_BATTLE = 0x00040000;
		//Protocol Type 0xxxxx0000
		public const uint PROTOCOL_TYPE_ALL = 0xffff0000;
		public const int PROTOCOL_TYPE_AUTH = 0x00020000;
		public const int PROTOCOL_TYPE_GAME = 0x00030000;
		public const int PROTOCOL_TYPE_BATTLE = 0x00040000;
		//Authentication Protocols for Clients 0x0001xxxx, xxxx start from 0x0000
		public const int P_AC_AUTH_CONNECT = 0x10001;
		public const int P_CA_AUTH_QUICK_LOGIN = 0x10002;
		public const int P_CA_AUTH_LOGIN = 0x10003;
		public const int P_AC_AUTH_LOGIN = 0x10004;
			public const int AUTH_LOGIN_SUCCESS = 0x110004;
			public const int AUTH_LOGIN_FAILED = 0x1010004;
			public const int AUTH_LOGIN_FAILED_INCORRECT_NAME_OR_PASSWORD = 0x1110004;
			public const int AUTH_LOGIN_FAILED_PASSWORD_IS_NULL = 0x1210004;
			public const int AUTH_LOGIN_FAILED_EMAIL_FORMAT_NOT_VALID = 0x1310004;
			public const int AUTH_LOGIN_FAILED_EMAIL_LENGTH_NOT_VALID = 0x1410004;
			public const int AUTH_LOGIN_FAILED_RANDOM_SEED_LENGTH_INVALID = 0x1510004;
			public const int AUTH_LOGIN_GET_CONNECTION_FAILED = 0x1610004;
			public const int AUTH_LOGIN_GET_AREA_LIST_FAILED = 0x1710004;
			public const int AUTH_LOGIN_FAILED_UDID_IS_NULL = 0x1810004;
		public const int P_CA_AUTH_CREATE_ACCOUNT = 0x10005;
		public const int P_AC_AUTH_CREATE_ACCOUNT = 0x10006;
			public const int AUTH_CREATE_ACCOUNT_SUCCESS = 0x110006;
			public const int AUTH_CREATE_ACCOUNT_FAILED = 0x1010006;
			public const int AUTH_CREATE_ACCOUNT_FAILED_EMAIL_EXSIT = 0x1110006;
			public const int AUTH_CREATE_ACCOUNT_FAILED_PASSWORD_IS_NULL = 0x1210006;
			public const int AUTH_CREATE_ACCOUNT_FAILED_EMAIL_FORMAT_NOT_VALID = 0x1310006;
			public const int AUTH_CREATE_ACCOUNT_FAILED_EMAIL_LENGTH_NOT_VALID = 0x1410006;
			public const int AUTH_CREATE_ACCOUNT_FAILED_RANDOM_SEED_LENGTH_INVALID = 0x1510006;
			public const int AUTH_CREATE_ACCOUNT_GET_CONNECTION_FAILED = 0x1610006;
			public const int AUTH_CREATE_ACCOUNT_GET_AREA_LIST_FAILED = 0x1710006;
			public const int AUTH_CREATE_ACCOUNT_FAILED_UDID_IS_NULL = 0x1810006;
		public const int P_CA_AUTH_BIND_ACCOUNT = 0x10007;
		public const int P_AC_AUTH_BIND_ACCOUNT = 0x10008;
			public const int AUTH_BIND_ACCOUNT_SUCCESS = 0x110008;
		public const int P_CA_AUTH_CHANGE_PASSWORD = 0x10009;
		public const int P_AC_AUTH_CHANGE_PASSWORD = 0x1000a;
			public const int AUTH_CHANGE_PASSWORD_SUCCESS = 0x11000a;
			public const int AUTH_CHANGE_PASSWORD_FAILED = 0x101000a;
			public const int AUTH_CHANGE_PASSWORD_FAILED_OLD_PASSWORD_ERROR = 0x111000a;

		//Game Protocols for Clients 0x0002xxxx, xxxx start from 0x0000
		public const int P_GC_GAME_ACK = 0x20001;
		public const int P_GC_GAME_CONNECT = 0x20002;
		public const int P_CG_GAME_LOGIN = 0x20003;
		public const int P_GC_GAME_LOGIN = 0x20004;
			public const int GAME_LOGIN_SUCCESS = 0x120004;
			public const int GAME_LOGIN_SUCCESS_ROLE_NOT_EXIST = 0x220004;
			public const int GAME_LOGIN_FAIL = 0x1020004;
		public const int P_CG_GAME_CREATE_ROLE = 0x20005;
		public const int P_GC_GAME_CREATE_ROLE = 0x20006;
			public const int GAME_CREATE_ROLE_SUCCESS = 0x120006;
			public const int GAME_CREATE_ROLE_FAIL_NAME_EXSIT = 0x1020006;
			public const int GAME_CREATE_ROLE_FAIL_NAME_NULL = 0x1120006;
			public const int GAME_CREATE_ROLE_FAIL_NAME_LENGTH_NOT_VALID = 0x1220006;
		public const int P_CG_USE_ITEM = 0x20007;
		public const int P_GC_USE_ITEM = 0x20008;
			public const int USE_ITEM_SUCCESS = 0x120008;
			public const int USE_ITEM_FAIL_CANNOT_USE = 0x1020008;
		public const int P_CG_SALE_ITEM = 0x20009;
		public const int P_GC_SALE_ITEM = 0x2000a;
			public const int SALE_ITEM_SUCCESS = 0x12000a;
			public const int SALE_ITEM_FAIL_ITEM_NOT_ENGOUTH = 0x102000a;
		public const int P_GC_BAG_LIST = 0x2000b;
		public const int P_GC_SHIP_LIST = 0x2000c;
		public const int P_CG_SEND_CHAT = 0x2000d;
		public const int P_GC_SEND_CHAT = 0x2000e;
			public const int SEND_CHAT_SUCCESS = 0x12000e;
			public const int SEND_CHAT_FAIL = 0x102000e;
			public const int SEND_CHAT_FAIL_COMMAND_NOT_EXIST = 0x112000e;
			public const int SEND_CHAT_FAIL_COMMAND_PARAM_ERROR = 0x122000e;
			public const int SEND_CHAT_FAIL_WORLD_CHAT_MIN_LV = 0x132000e;
			public const int SEND_CHAT_FAIL_WORLD_CHAT_MAX_COUNT = 0x142000e;
			public const int SEND_CHAT_FAIL_INTERVAL_TIME = 0x152000e;
			public const int SEND_CHAT_FAIL_CONTENT_EMPTY = 0x162000e;
			public const int SEND_CHAT_FAIL_CONTENT_MAX_LENGTH = 0x172000e;
		public const int P_GC_CHAT = 0x2000f;
		public const int P_GC_CHAT_LIST = 0x20010;
		public const int P_CG_SET_GAG_NAME_LIST = 0x20011;
		public const int P_GC_SET_GAG_NAME_LIST = 0x20012;
			public const int SET_GAG_NAME_LIST_SUCCESS = 0x120012;
			public const int SET_GAG_NAME_LIST_FAIL = 0x220012;
			public const int SET_GAG_NAME_LIST_FAIL_MAX_COUNT = 0x320012;
		public const int P_GC_GAG_NAME_LIST = 0x20013;
		public const int P_GC_MAIL_LIST = 0x20014;
		public const int P_CG_MAIL_RECV = 0x20015;
		public const int P_GC_MAIL_RECV = 0x20016;
			public const int MAIL_RECV_SUCCESS = 0x120016;
			public const int MAIL_RECV_FAIL = 0x1020016;
		public const int P_GC_QUEST_LIST = 0x20017;
		public const int P_CG_DELIVER_QUEST = 0x20018;
		public const int P_GC_DELIVER_QUEST = 0x20019;
			public const int DELIVER_QUEST_SUCCESS = 0x120019;
			public const int DELIVER_QUEST_FAIL_NOT_FOUND = 0x1020019;
			public const int DELIVER_QUEST_FAIL_NOT_FINISHED = 0x1120019;
			public const int DELIVER_QUEST_FAIL_HAS_DELIVERED = 0x1220019;
		public const int P_GC_BAG_UNSTACK_ITEM_UPDATE = 0x2001a;
		public const int P_CG_ROLE_MOVE = 0x2001b;
		public const int P_GC_ROLE_MOVE = 0x2001c;
		public const int P_GC_ROLE_IN_SCENE = 0x2001d;
		public const int P_GC_ROLE_OUT_SCENE = 0x2001e;
		public const int P_CG_ROLE_JUMP = 0x2001f;
		public const int P_GC_ROLE_JUMP = 0x20020;
		public const int P_CG_ROOM_LIST = 0x20021;
		public const int P_GC_ROOM_LIST = 0x20022;
		public const int P_CG_ROOM_CREATE = 0x20023;
		public const int P_GC_ROOM_CREATE = 0x20024;
			public const int ROOM_CREATE_SUCCESS = 0x120024;
			public const int ROOM_CREATE_FAIL_IN_ROOM = 0x1020024;
		public const int P_CG_ROOM_JOIN = 0x20025;
		public const int P_GC_ROOM_JOIN = 0x20026;
			public const int ROOM_JOIN_SUCCESS = 0x120026;
			public const int ROOM_JOIN_FAIL_IN_ROOM = 0x1020026;
			public const int ROOM_JOIN_FAIL_ROOMID_ERROR = 0x1120026;
		public const int P_GC_ROOM_ITEM_REFRESH = 0x20027;
		public const int P_CG_ROOM_ITEM_GET = 0x20028;
		public const int P_GC_ROOM_ITEM_GET = 0x20029;
			public const int ROOM_ITEM_GET_SUCCESS = 0x120029;
			public const int ROOM_ITEM_GET_FAIL_ITEM_NOT_EXSIT = 0x1020029;
			public const int ROOM_ITEM_GET_FAIL_ITEM_CANNOT_GET = 0x1120029;
		public const int P_CG_ROOM_ITEM_USE = 0x2002a;
		public const int P_GC_ROOM_ITEM_USE = 0x2002b;
			public const int ROOM_ITEM_USE_SUCCESS = 0x12002b;
			public const int ROOM_ITEM_USE_FAIL_ITEM_NOT_EXSIT = 0x102002b;
			public const int ROOM_ITEM_USE_FAIL_TARGET_NOT_AROUND = 0x112002b;
		public const int P_GC_ROOM_BATTLE_RESULT = 0x2002c;
		public const int P_CG_SCENE_QUIT = 0x2002d;
		public const int P_CG_ROOM_QUIT = 0x2002e;
		public const int P_GC_ROOM_QUIT = 0x2002f;
			public const int ROOM_QUIT_SUCCESS = 0x12002f;
			public const int ROOM_QUIT_FAIL_ROOM_NOT_EXSIT = 0x102002f;

		//server to server Protocols 0x0003xxxx, xxxx start from 0x0000
		public const int E_SS_REQ_SERVER_STATE_CHANGE = 0x30001;
		public const int E_SM_SERVER_REGISTER = 0x30002;
		public const int E_MS_SERVER_REGISTER = 0x30003;
		public const int E_AM_GET_GAME_AREA_LIST = 0x30004;
		public const int E_MA_GET_GAME_AREA_LIST = 0x30005;
		public const int E_GA_CHECK_TOKEN = 0x30006;
		public const int E_AG_CHECK_TOKEN = 0x30007;
		public const int E_GA_NOTIFY_CREATE_ROLE = 0x30008;
		public const int E_MG_GAME_SERVER_RELOAD = 0x30009;

	}
}
