//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: light framework (CF/Silverlight) enabled
    
// Generated from: protobuf/server.proto
// Note: requires additional types generated from: protobuf/auth.proto
// Note: requires additional types generated from: protobuf/role.proto
namespace com.kz.message.proto
{
  [global::ProtoBuf.ProtoContract(Name=@"ServerRegisterReq")]
  public partial class ServerRegisterReq : global::ProtoBuf.IExtensible
  {
    public ServerRegisterReq() {}
    
    private string _serverName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"serverName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string serverName
    {
      get { return _serverName; }
      set { _serverName = value; }
    }
    private bool _isReconnected;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"isReconnected", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isReconnected
    {
      get { return _isReconnected; }
      set { _isReconnected = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"ServerRegisterRes")]
  public partial class ServerRegisterRes : global::ProtoBuf.IExtensible
  {
    public ServerRegisterRes() {}
    
    private com.kz.message.proto.ServerConfigPro _selfConfig;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"selfConfig", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public com.kz.message.proto.ServerConfigPro selfConfig
    {
      get { return _selfConfig; }
      set { _selfConfig = value; }
    }
    private readonly global::System.Collections.Generic.List<com.kz.message.proto.DepandenceServerPro> _depandences = new global::System.Collections.Generic.List<com.kz.message.proto.DepandenceServerPro>();
    [global::ProtoBuf.ProtoMember(2, Name=@"depandences", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.kz.message.proto.DepandenceServerPro> depandences
    {
      get { return _depandences; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"ServerConfigPro")]
  public partial class ServerConfigPro : global::ProtoBuf.IExtensible
  {
    public ServerConfigPro() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _serverType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"serverType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int serverType
    {
      get { return _serverType; }
      set { _serverType = value; }
    }
    private string _ipForServer;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"ipForServer", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ipForServer
    {
      get { return _ipForServer; }
      set { _ipForServer = value; }
    }
    private int _portForServer;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"portForServer", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int portForServer
    {
      get { return _portForServer; }
      set { _portForServer = value; }
    }
    private int _status;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int status
    {
      get { return _status; }
      set { _status = value; }
    }
    private int _area;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"area", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int area
    {
      get { return _area; }
      set { _area = value; }
    }
    private int _portForClient;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"portForClient", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int portForClient
    {
      get { return _portForClient; }
      set { _portForClient = value; }
    }
    private string _serverDefined = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"serverDefined", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string serverDefined
    {
      get { return _serverDefined; }
      set { _serverDefined = value; }
    }
    private string _careServerList = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"careServerList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string careServerList
    {
      get { return _careServerList; }
      set { _careServerList = value; }
    }
    private long _createTime;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"createTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long createTime
    {
      get { return _createTime; }
      set { _createTime = value; }
    }
    private string _serverName;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"serverName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string serverName
    {
      get { return _serverName; }
      set { _serverName = value; }
    }
    private bool _isNewServer;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"isNewServer", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isNewServer
    {
      get { return _isNewServer; }
      set { _isNewServer = value; }
    }
    private bool _isRecommendServer;
    [global::ProtoBuf.ProtoMember(14, IsRequired = true, Name=@"isRecommendServer", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isRecommendServer
    {
      get { return _isRecommendServer; }
      set { _isRecommendServer = value; }
    }
    private string _ipForClient;
    [global::ProtoBuf.ProtoMember(15, IsRequired = true, Name=@"ipForClient", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ipForClient
    {
      get { return _ipForClient; }
      set { _ipForClient = value; }
    }
    private string _areaName = "";
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"areaName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string areaName
    {
      get { return _areaName; }
      set { _areaName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"DepandenceServerPro")]
  public partial class DepandenceServerPro : global::ProtoBuf.IExtensible
  {
    public DepandenceServerPro() {}
    
    private int _serverId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"serverId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int serverId
    {
      get { return _serverId; }
      set { _serverId = value; }
    }
    private int _serverType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"serverType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int serverType
    {
      get { return _serverType; }
      set { _serverType = value; }
    }
    private string _ipForServer;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"ipForServer", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ipForServer
    {
      get { return _ipForServer; }
      set { _ipForServer = value; }
    }
    private int _portForServer;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"portForServer", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int portForServer
    {
      get { return _portForServer; }
      set { _portForServer = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"AuthTokenReq")]
  public partial class AuthTokenReq : global::ProtoBuf.IExtensible
  {
    public AuthTokenReq() {}
    
    private long _sessionId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"sessionId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long sessionId
    {
      get { return _sessionId; }
      set { _sessionId = value; }
    }
    private long _accountId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"accountId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long accountId
    {
      get { return _accountId; }
      set { _accountId = value; }
    }
    private string _token;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string token
    {
      get { return _token; }
      set { _token = value; }
    }
    private int _areaId;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"areaId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int areaId
    {
      get { return _areaId; }
      set { _areaId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"AuthTokenRes")]
  public partial class AuthTokenRes : global::ProtoBuf.IExtensible
  {
    public AuthTokenRes() {}
    
    private long _sessionId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"sessionId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long sessionId
    {
      get { return _sessionId; }
      set { _sessionId = value; }
    }
    private com.kz.message.proto.AccountPro _account = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.kz.message.proto.AccountPro account
    {
      get { return _account; }
      set { _account = value; }
    }
    private com.kz.message.proto.DeviceInfoPro _deviceInfo = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"deviceInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.kz.message.proto.DeviceInfoPro deviceInfo
    {
      get { return _deviceInfo; }
      set { _deviceInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"NotifyCreateRoleReq")]
  public partial class NotifyCreateRoleReq : global::ProtoBuf.IExtensible
  {
    public NotifyCreateRoleReq() {}
    
    private int _areaId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"areaId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int areaId
    {
      get { return _areaId; }
      set { _areaId = value; }
    }
    private long _accountId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"accountId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long accountId
    {
      get { return _accountId; }
      set { _accountId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"AccountPro")]
  public partial class AccountPro : global::ProtoBuf.IExtensible
  {
    public AccountPro() {}
    
    private long _accountId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"accountId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long accountId
    {
      get { return _accountId; }
      set { _accountId = value; }
    }
    private string _email;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"email", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string email
    {
      get { return _email; }
      set { _email = value; }
    }
    private int _lastAreaId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"lastAreaId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int lastAreaId
    {
      get { return _lastAreaId; }
      set { _lastAreaId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"GameAreaList")]
  public partial class GameAreaList : global::ProtoBuf.IExtensible
  {
    public GameAreaList() {}
    
    private readonly global::System.Collections.Generic.List<com.kz.message.proto.ServerConfigPro> _areaList = new global::System.Collections.Generic.List<com.kz.message.proto.ServerConfigPro>();
    [global::ProtoBuf.ProtoMember(1, Name=@"areaList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.kz.message.proto.ServerConfigPro> areaList
    {
      get { return _areaList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}